source "https://rubygems.org"

gem "tilt"
gem "json"
gem "libv8"
gem "therubyracer", :git => "git://github.com/cowboyd/therubyracer.git"
gem "less"
gem "coffee-script"
gem "haml"
gem "rack"
gem "rake-pipeline", :git => "https://github.com/livingsocial/rake-pipeline.git"
gem "rake-pipeline-web-filters", :git => "https://github.com/wycats/rake-pipeline-web-filters.git"